In [1]:
import pandas as pd
import re

# 파일 불러오기
hospital = pd.read_csv("C:/Users/user/Desktop/Final_Project/data/health_care/new_hospital_xy.csv")
hospital

,지번주소,도로명주소,도로명우편번호,사업자명,UPTAENM,경도,위도
0,NaN,"서울특별시 강동구 강동대로 243, 풍원빌딩 (성내동)",5408,치휴한방병원,한방병원,127.132975,37.522396
1,NaN,서울특별시 강동구 천호대로 1151 (길동),5356,고은빛여성병원,병원,127.139336,37.534156
2,NaN,"서울특별시 강동구 양재대로 1525, 명품빌딩 (천호동)",5316,올바른서울병원,병원,127.141295,37.542100
3,서울특별시 강동구 길동 459번지 1호,서울특별시 강동구 천호대로 1133 (길동),5355,남기세병원,병원,127.137513,37.534689
4,NaN,서울특별시 강동구 천호대로 1044 (성내동),5379,리더스병원,병원,127.127728,37.536947
...,...,...,...,...,...,...,...
1089,NaN,서울특별시 강동구 동남로 892 (상일동),5278,강동경희대학교한방병원,한방병원,127.157085,37.552046
1090,서울특별시 강동구 길동 412-10 SC MEDI TOWER,"서울특별시 강동구 양재대로 1461, SC MEDI TOWER 2,4,5층 (길동)",5353,위드힘병원,병원,127.139096,37.536390
1091,서울특별시 강동구 천호동 421번지 4호 행복타워빌딩,"서울특별시 강동구 구천면로 202, 행복타워빌딩 B2,2,3,4,6층 (천호동)",5329,강동우리들요양병원,요양병원(일반요양병원),127.127095,37.540101
1092,서울특별시 강동구 고덕동 297-1 원케어메디컬타운,"서울특별시 강동구 고덕로 295-60, 원케어메디컬타운 (고덕동)",5225,서울숲요양병원,요양병원(일반요양병원),127.158039,37.556120
1093,NaN,"서울특별시 강동구 양재대로 1596, 3~6층 (명일동)",5295,봄담한방병원,한방병원,NaN,NaN

In [3]:
print("결측치 개수:")
print(hospital.isnull().sum())

결측치 개수:
지번주소       408
도로명주소        0
도로명우편번호      0
사업자명         0
UPTAENM      0
경도         130
위도         130
dtype: int64

In [4]:
hospital.drop(columns=['지번주소', '도로명우편번호', 'UPTAENM'], inplace=True)

In [5]:
hospital['category'] = '병원'

In [6]:
hospital.rename(columns={'위도': 'latitude', '경도': 'longitude', '도로명주소': 'road_address', '사업자명': 'business_name'}, inplace=True)

In [7]:
print(hospital)

                                        road_address business_name  \
0                     서울특별시 강동구 강동대로 243, 풍원빌딩 (성내동)        치휴한방병원
1                           서울특별시 강동구 천호대로 1151 (길동)       고은빛여성병원
2                    서울특별시 강동구 양재대로 1525, 명품빌딩 (천호동)       올바른서울병원
3                           서울특별시 강동구 천호대로 1133 (길동)         남기세병원
4                          서울특별시 강동구 천호대로 1044 (성내동)         리더스병원
...                                              ...           ...
1089                         서울특별시 강동구 동남로 892 (상일동)   강동경희대학교한방병원
1090  서울특별시 강동구 양재대로 1461, SC MEDI TOWER 2,4,5층 (길동)         위드힘병원
1091    서울특별시 강동구 구천면로 202, 행복타워빌딩 B2,2,3,4,6층 (천호동)     강동우리들요양병원
1092            서울특별시 강동구 고덕로 295-60, 원케어메디컬타운 (고덕동)       서울숲요양병원
1093                 서울특별시 강동구 양재대로 1596, 3~6층 (명일동)        봄담한방병원

       longitude   latitude category
0     127.132975  37.522396       병원
1     127.139336  37.534156       병원
2     127.141295  37.542100       병원
3     127.137513  37.534689       병원
4     127.127728  37.536947       병원
...          ...        ...      ...
1089  127.157085  37.552046       병원
1090  127.139096  37.536390       병원
1091  127.127095  37.540101       병원
1092  127.158039  37.556120       병원
1093         NaN        NaN       병원

[1094 rows x 5 columns]

In [8]:
print("결측치 개수:")
print(hospital.isnull().sum())

결측치 개수:
road_address       0
business_name      0
longitude        130
latitude         130
category           0
dtype: int64

In [9]:
hospital = hospital.dropna(subset=['longitude', 'latitude'])

In [10]:
print("결측치 개수:")
print(hospital.isnull().sum())

결측치 개수:
road_address     0
business_name    0
longitude        0
latitude         0
category         0
dtype: int64

In [11]:
print(hospital)

                                        road_address business_name  \
0                     서울특별시 강동구 강동대로 243, 풍원빌딩 (성내동)        치휴한방병원
1                           서울특별시 강동구 천호대로 1151 (길동)       고은빛여성병원
2                    서울특별시 강동구 양재대로 1525, 명품빌딩 (천호동)       올바른서울병원
3                           서울특별시 강동구 천호대로 1133 (길동)         남기세병원
4                          서울특별시 강동구 천호대로 1044 (성내동)         리더스병원
...                                              ...           ...
1088                       서울특별시 강동구 동남로 892 (상일제1동)   강동경희대학교치과병원
1089                         서울특별시 강동구 동남로 892 (상일동)   강동경희대학교한방병원
1090  서울특별시 강동구 양재대로 1461, SC MEDI TOWER 2,4,5층 (길동)         위드힘병원
1091    서울특별시 강동구 구천면로 202, 행복타워빌딩 B2,2,3,4,6층 (천호동)     강동우리들요양병원
1092            서울특별시 강동구 고덕로 295-60, 원케어메디컬타운 (고덕동)       서울숲요양병원

       longitude   latitude category
0     127.132975  37.522396       병원
1     127.139336  37.534156       병원
2     127.141295  37.542100       병원
3     127.137513  37.534689       병원
4     127.127728  37.536947       병원
...          ...        ...      ...
1088  127.157085  37.552046       병원
1089  127.157085  37.552046       병원
1090  127.139096  37.536390       병원
1091  127.127095  37.540101       병원
1092  127.158039  37.556120       병원

[964 rows x 5 columns]

In [13]:
hospital.to_csv("../data/health_care/hospital.csv", index=False, encoding='utf-8')

In [14]:
hospital = pd.read_csv("../data/health_care/hospital.csv")
pharmacy = pd.read_csv("../data/health_care/pharmacy.csv")
print(hospital)
print(pharmacy)

                                       road_address business_name   longitude  \
0                    서울특별시 강동구 강동대로 243, 풍원빌딩 (성내동)        치휴한방병원  127.132975
1                          서울특별시 강동구 천호대로 1151 (길동)       고은빛여성병원  127.139336
2                   서울특별시 강동구 양재대로 1525, 명품빌딩 (천호동)       올바른서울병원  127.141295
3                          서울특별시 강동구 천호대로 1133 (길동)         남기세병원  127.137513
4                         서울특별시 강동구 천호대로 1044 (성내동)         리더스병원  127.127728
..                                              ...           ...         ...
959                       서울특별시 강동구 동남로 892 (상일제1동)   강동경희대학교치과병원  127.157085
960                         서울특별시 강동구 동남로 892 (상일동)   강동경희대학교한방병원  127.157085
961  서울특별시 강동구 양재대로 1461, SC MEDI TOWER 2,4,5층 (길동)         위드힘병원  127.139096
962    서울특별시 강동구 구천면로 202, 행복타워빌딩 B2,2,3,4,6층 (천호동)     강동우리들요양병원  127.127095
963            서울특별시 강동구 고덕로 295-60, 원케어메디컬타운 (고덕동)       서울숲요양병원  127.158039

      latitude category
0    37.522396       병원
1    37.534156       병원
2    37.542100       병원
3    37.534689       병원
4    37.536947       병원
..         ...      ...
959  37.552046       병원
960  37.552046       병원
961  37.536390       병원
962  37.540101       병원
963  37.556120       병원

[964 rows x 5 columns]
                                        road_address business_name  \
0     서울특별시 강동구 천호대로 1024, 힐스테이트 천호역 젠트리스 331호 (성내동)        365연약국
1                 서울특별시 동작구 사당로 215, 서림빌딩 202호 (사당동)        다나은 약국
2                     서울특별시 송파구 올림픽로 362, 102호 (방이동)        잠실하나약국
3                          서울특별시 중구 퇴계로 53, 1층 (남창동)       남대문대형약국
4                         서울특별시 양천구 지양로 74, 1층 (신월동)          뿌리약국
...                                              ...           ...
5610       서울특별시 강동구 양재대로 1360, 포레온스테이션5 3067호 (둔촌동)          지안약국
5611  서울특별시 강동구 천호대로 1024, 힐스테이트 천호역 젠트리스 207호 (성내동)     힐스테이트2층약국
5612             서울특별시 강동구 양재대로 1360, 3층 3084호 (둔촌동)       포레온새싹약국
5613             서울특별시 강동구 양재대로 1360, 1층 1005호 (둔촌동)       포레온이화약국
5614   서울특별시 강동구 양재대로 1300, 3층 3306호 (둔촌동, 올림픽파크포레온)       포레온누리약국

       longitude   latitude category
0     127.125729  37.537374       약국
1     126.972345  37.484459       약국
2     127.110381  37.516381       약국
3     126.978063  37.558696       약국
4     126.833816  37.522267       약국
...          ...        ...      ...
5610  127.137046  37.527476       약국
5611  127.125729  37.537374       약국
5612  127.137046  37.527476       약국
5613  127.137046  37.527476       약국
5614  127.140291  37.524968       약국

[5615 rows x 5 columns]

In [15]:
health_care_df = pd.concat([hospital, pharmacy], ignore_index=True)

In [17]:
health_care_df.reset_index(drop=True, inplace=True)
health_care_df.insert(0, 'id', health_care_df.index + 1)

In [18]:
health_care_df

,id,road_address,business_name,longitude,latitude,category
0,1,"서울특별시 강동구 강동대로 243, 풍원빌딩 (성내동)",치휴한방병원,127.132975,37.522396,병원
1,2,서울특별시 강동구 천호대로 1151 (길동),고은빛여성병원,127.139336,37.534156,병원
2,3,"서울특별시 강동구 양재대로 1525, 명품빌딩 (천호동)",올바른서울병원,127.141295,37.542100,병원
3,4,서울특별시 강동구 천호대로 1133 (길동),남기세병원,127.137513,37.534689,병원
4,5,서울특별시 강동구 천호대로 1044 (성내동),리더스병원,127.127728,37.536947,병원
...,...,...,...,...,...,...
6574,6575,"서울특별시 강동구 양재대로 1360, 포레온스테이션5 3067호 (둔촌동)",지안약국,127.137046,37.527476,약국
6575,6576,"서울특별시 강동구 천호대로 1024, 힐스테이트 천호역 젠트리스 207호 (성내동)",힐스테이트2층약국,127.125729,37.537374,약국
6576,6577,"서울특별시 강동구 양재대로 1360, 3층 3084호 (둔촌동)",포레온새싹약국,127.137046,37.527476,약국
6577,6578,"서울특별시 강동구 양재대로 1360, 1층 1005호 (둔촌동)",포레온이화약국,127.137046,37.527476,약국
6578,6579,"서울특별시 강동구 양재대로 1300, 3층 3306호 (둔촌동, 올림픽파크포레온)",포레온누리약국,127.140291,37.524968,약국

In [19]:
health_care_df.to_csv("../data/health_care/health_care.csv", index=False, encoding='utf-8')

In [20]:
import pandas as pd

df = pd.read_csv("../data/health_care/health_care.csv")

print("전체 컬럼별 결측치 개수:")
print(df.isnull().sum())

print("\n 결측치가 있는 행:")
print(df[df.isnull().any(axis=1)])

전체 컬럼별 결측치 개수:
id               0
road_address     0
business_name    0
longitude        0
latitude         0
category         0
dtype: int64

 결측치가 있는 행:
Empty DataFrame
Columns: [id, road_address, business_name, longitude, latitude, category]
Index: []